### ISSUE TITLE
sass 基本语法

### ISSUE THREAD

**Issue by ifyour** [ifyour/learn-sass-compass#3]
### 变量
$变量名
```scss
$base-size: 16px;
font-size: $base-size;
```
### @import
加上 `_` 代表该文件不需要被编译, 例如我们把变量文件抽离出来, 然后使用 `@import` 导入该文件.

```scss
# _variables.scss 文件
$base-size: 16px;
```
```scss
# main.scss 文件
@import "_variables"
font-size: $base-size;
```
scss 文件中的 `@import` 区别于 css 文件中的 `@import` 指令.

css 文件中的 `@import` 弊端:
- 引入的文件必须放在最前面
- 阻塞加载, 必须等前面的文件加载完毕, 才能加载后面的文件

### 注释
- `//` 单行注释
- `/**/` 多行注释, 会被输出到最终生成的 css 文件中

### 嵌套
- 支持 `{}` 的文件嵌套
- 使用 `&` 指代自身的引用
```css
.main {
    font-size: 18px;
    a {
        color: red;
        &:hover {
            color: green;
        }
    }
}
```
### mixin 混合
编写:
```scss
@mixin col ($width: 50%) {
    width: $width;
    float: left;
}
```
调用:
```main.scss
.main {
    @include: col(25%);
}
```

### @extend 继承
```scss
.err1 {
  font-size: 12px;
}

.err2 {
  color: #f00;
}

.err3 {
  background-color: #000;
}

.my-err {
  @extend .err1;
  @extend .err2;
  @extend .err3;
}
```

### 避免大量嵌套
- 增加了样式修饰的权重
- 制造了这种样式的位置依赖

使用 sass 的 `@at-root`
```scss
.main {
    font-size: 18px;
    @at-root: {
        a {
            color: red;
            &:hover {
                color: green;
            }
        }
    }
}
```
使用 `@at-root` 后, 生成 css 时, 在其内部的修饰会被放到根修饰中.
