### ISSUE TITLE
compass 各模块的基本用法

### ISSUE THREAD

**Issue by ifyour** [ifyour/learn-sass-compass#4]
### compass 插件的引入
使用插件, 相比引入单独的文件, 具备跟多的灵活性. 引入一个插件, 相当于引入一个 gem 包文件. 引入时, 需要配置 config.rb 文件. 例如 `normalize` 的引入.
1. 安装 compass 插件 `compass-normallize`
```bash
gem install compass-normallize
```
2. 配置 `config.rb` 在顶部 require 即可
```
require 'compass-normalize'
```
3. 在 `.scss` 顶部引入
```scss
@import "normalize";
```
用起来其实和 npm 用法差不多. 慢慢体会.

#### reset 和 normallize 的区别
- reset 是重置所有样式的属相, 相当于归零
- normalize 是统一各个浏览器, 使表现统一 (推荐)

### compass 模块组成
- CSS3: 提供跨浏览器的 CSS3 能力
- Helpers: 内含一系列函数
- Typography: 修饰文本样式
- Utilities: 辅助函数，多为 mixin
- Browser: 配置 compass 默认支持哪些浏览器，支持到哪个版本，一旦修改即影响其他模块的输出
- Reset: 重置样式
- Layout: 页面布局控制能力

其中 `Reset` 和 `Layout` 需要单独引入. 在使用 compass 时, 可以单独引入其中一个小的模块. 
```bash
@import "compass/layout";
```
具体每个模块的 `mixin` 使用教程, [点击这里](http://compass-style.org/reference/compass/)去官网查看. 同时, 我也把各个 mixin 的用法做了一些 [Demo](https://github.com/ifyour/learn-sass-compass/blob/master/learn-compass/sass/screen.scss) 详细可以看我代码的注释.

#### 使用举例 code 1
```scss
// 引入 compass 的 css3 模块, 调用盒子阴影的 mixin
@import "compass/css3"
.box-shadows {
    @include box-shadow (1px 1px 2px 3px #ccc);
}
```
最终生成结果:
```css
.box-shadows {
  -moz-box-shadow: 1px 1px 2px 3px #ccc;
  -webkit-box-shadow: 1px 1px 2px 3px #ccc;
  box-shadow: 1px 1px 2px 3px #ccc;
}
```
#### 使用举例 code 2
```scss
@import "compass/support";
$supported-browsers: chrome ie firefox;
$browser-nimimum-sersions: ("ie" : "8");

// css3 的 inline-bloc 垮浏览器兼容
// 比如解决了 IE 对 inline-block 的支持
.test-inline-block {
    @include inline-block();
}
// css3 的 opacity 透明度 垮浏览器兼容
.test-opacity {
    @include opacity(.3);
}
```
最终生成
```css
.test-inline-block {
  display: inline-block;
  vertical-align: middle;
  *vertical-align: auto;
  *zoom: 1;
  *display: inline;
}
.test-opacity {
  filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=30);
  opacity: 0.3;
}
```
